### PR TITLE
pin shapely <2.0.0 (temporary fix) so the package builds and installs correctly

### PR DESCRIPTION
**Pull request by valeriupredoi**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
~* [ ] Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Issue documented (specifically to ESMValTool) in https://github.com/ESMValGroup/ESMValTool/issues/2992 but do have a look at the ESMValCore issue linked from within. This pin should ideally be suppressed once the Shapely guys do something about itor we have patched and rebuilt Core (hopefully not the case).

### CODE REVIEW

**Comment by valeriupredoi** [comment]
@conda-forge-admin, please rerender

**Comment by valeriupredoi** [comment]
@schlunma the package build fails with some very [dodgy mlr-test-related issues](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=636309&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=8615) - before I start digging deeper, I thought I'd ask you, maybe you know what's that all about and all I need to do is pin something? :beer:

**Comment by schlunma** [comment]
Well, the first six are the same as reported in https://github.com/ESMValGroup/ESMValTool/issues/2959 (fixed in https://github.com/ESMValGroup/ESMValTool/pull/2961) and the remaining ones have been fixed https://github.com/ESMValGroup/ESMValTool/pull/2900 (rather by accident :joy:).

**Comment by valeriupredoi** [comment]
righto! Cheers, bud - problem is I can't change code here, so, would a pin of `sklearn` work maybe?

**Comment by schlunma** [comment]
Probably, try `<1.2`, looks like this is the version that removed all the deprecated features.

**Comment by valeriupredoi** [comment]
shweet, thanks, man! Let me try :beer:

**Comment by valeriupredoi** [comment]
green :green_circle: yay, cheers, Manu! :beer:

**Review by bouweandela — APPROVED** [review]

**Review by schlunma — APPROVED** [review]

**Comment by valeriupredoi** [comment]
when it rains, it pours (with reviewers) - cheers, gents :beer:

**Pull request merged**
