### PR TITLE
[v2.11.0.build=1] pin cartopy<0.24 and curl<8.10 and pandas<2.2.0 and change to build 1

### PR DESCRIPTION
**Pull request by valeriupredoi**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* ~[ ] Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Changes needed via upstream by https://github.com/ESMValGroup/ESMValTool/pull/3768 and https://github.com/ESMValGroup/ESMValTool/pull/3755
Changes tested upstream and plugged in `v2.11.x` branch via https://github.com/ESMValGroup/ESMValTool/pull/3770
Pandas pinned (hopefully for the last time, upstream ESMValCore fix is now in https://github.com/ESMValGroup/ESMValCore/pull/2529)
Also pinned to Python<3.12 just to be as close as the tested ESMValTool 2.11

### CODE REVIEW

**Comment by valeriupredoi** [comment]
@conda-forge-admin, please rerender

**Comment by valeriupredoi** [comment]
> > For **recipe/meta.yaml**:
> > ```
> > * Use `importlib-metadata` instead of `importlib_metadata`
> > 
> > * No valid build backend found for Python recipe for package `esmvaltool-python` using `pip`. Python recipes using `pip` need to explicitly specify a build backend in the `host` section. If your recipe has built with only `pip` in the `host` section in the past, you likely should add `setuptools` to the `host` section of your recipe.
> > ```
> 
> Do we want to consider these?

no - we don't have an `esmvaltool-python` PyPI package, and we specifically want to pin `importlib_metadata` and not the one with dash in it :beer:

**Review by schlunma — APPROVED** [review]
LGTM! I don't really like this hard pin on the Python version to be honest, but it's probably safer that way.

I am also still not quite sure if we can really dismiss the comments by @conda-forge-admin so easily, but let's discuss this when we release v2.12.0.

Thanks V for taking care of this!

**Review by bettina-gier — APPROVED** [review]
Since you asked me to look at it, have an approve :+1:
packages are pinned to what was discussed to avoid issues, can't really comment on the comments. Hard pin on python will only be until the next release so should be fine.

**Comment by valeriupredoi** [comment]
oh I absolutely hate the Python<3.12 pin myself, bud, especially now that we have full functionality for it in the main branch - but, I reckon better safe than sorry - we can always come back and rebuild with it, but you know - this way is the closest one can get to the actual 2.11 (bar a lock file that would completely freeze the deps and builds at the moment of 2.11 release).

About what c-f is suggesting - it's not possible, since `importlib-metadata` is actually a different package https://anaconda.org/conda-forge/importlib_metadata/files vs https://anaconda.org/conda-forge/importlib-metadata/files - not sure myself what the differences between the two pkgs are but, I know fr a fact we need to pin the underscore one :beer:

**Comment by valeriupredoi** [comment]
cheers Manu :beer:

**Comment by valeriupredoi** [comment]
> Since you asked me to look at it, have an approve 👍 packages are pinned to what was discussed to avoid issues, can't really comment on the comments. Hard pin on python will only be until the next release so should be fine.

excellent, cheers, Tina :beer:

**Pull request merged**
